// Copyright (c) 2026 ArtisticSW2026. All Rights Reserved.
// Auto-generated by Python Kelvin Wake Gradient Atlas Baker (Method 2 / M4-A)
// SHA256 (RGBA16F Payload): 6e917f247989ff448ccc4dfe5a46444b726050bb55cd0b3f40a75947b022b34a

#pragma once

#define KELVIN_ATLAS_VERSION "M4A_2.0_AnalyticalGradient"
#define KELVIN_ATLAS_NUM_SLICES 12
#define KELVIN_ATLAS_RES_U 512
#define KELVIN_ATLAS_RES_V 256

#define KELVIN_ATLAS_U_MIN 0.000000f
#define KELVIN_ATLAS_U_MAX 10.000000f
#define KELVIN_ATLAS_U_RANGE 10.000000f

#define KELVIN_ATLAS_V_MIN -3.000000f
#define KELVIN_ATLAS_V_MAX 3.000000f
#define KELVIN_ATLAS_V_RANGE 6.000000f

#define KELVIN_ATLAS_GLOBAL_SCALE 35.433288f

// Texture Channel Layout:
// R = Height (zeta / Z_peak)
// G = dzeta/du / Z_peak (Downstream Slope)
// B = dzeta/dv / Z_peak (Lateral Slope)
// A = Mask (1.0)
#define KELVIN_ATLAS_HAS_GRADIENT 1

#ifdef __cplusplus
namespace ArtisticSW::KelvinAtlas
{
    static const float FroudeSlices[12] = { 0.2000f, 0.3000f, 0.4000f, 0.5000f, 0.6000f, 0.7000f, 0.8000f, 1.0000f, 1.2500f, 1.5000f, 1.7500f, 2.0000f };
    static const float SliceMaxAmplitudes[12] = { 0.000001f, 0.031517f, 0.483689f, 1.387197f, 2.537855f, 3.910964f, 5.534106f, 9.651471f, 16.016631f, 21.974640f, 27.183469f, 35.433288f };
    static const float SliceMaxGradientsU[12] = { 0.000000f, 0.205753f, 3.379763f, 10.747999f, 22.219126f, 38.874684f, 62.147227f, 133.061239f, 264.923110f, 393.515072f, 575.107560f, 892.910042f };
    static const float SliceMaxGradientsV[12] = { 0.000000f, 0.034876f, 1.007260f, 4.922084f, 14.318064f, 32.668597f, 66.091457f, 207.800224f, 489.925207f, 1530.037137f, 3465.310130f, 5840.024938f };

    inline int32 GetNumSlices() { return 12; }
    inline float GetUMin() { return 0.000000f; }
    inline float GetUMax() { return 10.000000f; }
    inline float GetVMin() { return -3.000000f; }
    inline float GetVMax() { return 3.000000f; }
}
#endif
