[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=B07A3091402F112924DCCBB3D1607B78
ProjectName=Third Person Game Template

# PlayerState의 기본 동기화 빈도 설정
[/Script/ClassFeature.BasePlayerState]
BaseNetUpdateFrequency=20.0f
