[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=B07A3091402F112924DCCBB3D1607B78
ProjectName=Third Person Game Template

# PlayerState의 기본 동기화 빈도 설정
[/Script/ClassFeature.BasePlayerState]
BaseNetUpdateFrequency=20.0f

# Craft의 투척 네트워크 동기화 빈도 설정
[/Script/ClassFeature.ThrowItem]
ProjectileNetUpdateFrequency=20.f

# Player의 주변 상호작용 Object 감지 주기
[/Script/ClassFeature.BasePlayer]
InteractionScanInterval=0.1f

[/Script/ArtisticSWCore.ItemSettings]
ItemFeatureDataTable=/Game/Blueprints/Item/ItemFeatureDataTable.ItemFeatureDataTable
ItemAssetRegistry=/Game/Blueprints/Item/DA_ItemData.DA_ItemData

[/Script/ArtisticSWCore.Settings_Item]
ItemFeatureDataTable=/Game/Blueprints/Item/ItemFeatureDataTable.ItemFeatureDataTable
ItemAssetRegistry=/Game/Blueprints/Item/DA_ItemData.DA_ItemData
CraftingRecipeDataTable=/Game/Blueprints/Item/DT_CraftingRecipes.DT_CraftingRecipes

[/Script/UnrealEd.ProjectPackagingSettings]
+DirectoriesToAlwaysStageAsNonUFS=(Path="New/Water/Realistic_Water/Kelvin")
[/Script/GameplayAbilities.AbilitySystemGlobals]
+GameplayCueNotifyPaths=/Game/GameplayCues

