"""
atlas_baker.py - Production Gradient Atlas Baker for Unreal Engine
Bakes multi-slice Froude atlas of normalized signed heights and analytical gradients:
  - Channel 0 (R): Normalized Signed Height zeta / Z_peak
  - Channel 1 (G): Normalized Downstream Gradient (dzeta/du) / Z_peak
  - Channel 2 (B): Normalized Lateral Gradient (dzeta/dv) / Z_peak
  - Channel 3 (A): Validity Mask / Peak Scale

Generates:
  1. kelvin_wake_atlas_gradient_fp16.bin: Flat raw RGBA16F / FP16 binary payload
  2. kelvin_wake_atlas_fp16.bin: Flat raw R16F / FP16 binary payload (backward compatible)
  3. kelvin_wake_atlas_meta.json: Full slice, gradient, and domain metadata
  4. KelvinAtlasGradientConstants.h: Auto-generated C++ & HLSL header
  5. atlas_slices_preview.png: Montage of all baked Froude slices (Elevation & Normals)
"""

import os
import site
import sys

user_site = site.getusersitepackages()
if os.path.exists(user_site) and user_site not in sys.path:
    sys.path.insert(0, user_site)

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
import json
import hashlib
from pathlib import Path
from typing import List

from baker_core import (
    GaussLegendreVectorizedEvaluator,
    KelvinDomainConfig,
    KELVIN_CUSP_ANGLE_RAD
)


DEFAULT_FROUDE_SLICES = [
    0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 1.00, 1.25, 1.50, 1.75, 2.00
]


def generate_cpp_hlsl_header(
    meta: dict,
    header_path: Path
):
    """Generates unified C++ / HLSL constant definitions header with gradient support."""
    slices = meta["FroudeSlices"]
    n_slices = meta["NumSlices"]
    res_u = meta["ResolutionU"]
    res_v = meta["ResolutionV"]
    u_min = meta["Domain"]["UMin"]
    u_max = meta["Domain"]["UMax"]
    v_min = meta["Domain"]["VMin"]
    v_max = meta["Domain"]["VMax"]
    global_scale = meta["GlobalScaleFactor"]

    slice_arr_str = ", ".join(f"{f:.4f}f" for f in slices)
    max_amp_arr_str = ", ".join(f"{a:.6f}f" for a in meta["SliceMaxAmplitudes"])
    max_grad_u_str = ", ".join(f"{a:.6f}f" for a in meta["SliceMaxGradientsU"])
    max_grad_v_str = ", ".join(f"{a:.6f}f" for a in meta["SliceMaxGradientsV"])

    header_content = f"""// Copyright (c) 2026 ArtisticSW2026. All Rights Reserved.
// Auto-generated by Python Kelvin Wake Gradient Atlas Baker (Method 2 / M4-A)
// SHA256 (RGBA16F Payload): {meta["PayloadSHA256"]}

#pragma once

#define KELVIN_ATLAS_VERSION "{meta["BakerVersion"]}"
#define KELVIN_ATLAS_NUM_SLICES {n_slices}
#define KELVIN_ATLAS_RES_U {res_u}
#define KELVIN_ATLAS_RES_V {res_v}

#define KELVIN_ATLAS_U_MIN {u_min:.6f}f
#define KELVIN_ATLAS_U_MAX {u_max:.6f}f
#define KELVIN_ATLAS_U_RANGE {u_max - u_min:.6f}f

#define KELVIN_ATLAS_V_MIN {v_min:.6f}f
#define KELVIN_ATLAS_V_MAX {v_max:.6f}f
#define KELVIN_ATLAS_V_RANGE {v_max - v_min:.6f}f

#define KELVIN_ATLAS_GLOBAL_SCALE {global_scale:.6f}f

// Texture Channel Layout:
// R = Height (zeta / Z_peak)
// G = dzeta/du / Z_peak (Downstream Slope)
// B = dzeta/dv / Z_peak (Lateral Slope)
// A = Mask (1.0)
#define KELVIN_ATLAS_HAS_GRADIENT 1

#ifdef __cplusplus
namespace ArtisticSW::KelvinAtlas
{{
    static const float FroudeSlices[{n_slices}] = {{ {slice_arr_str} }};
    static const float SliceMaxAmplitudes[{n_slices}] = {{ {max_amp_arr_str} }};
    static const float SliceMaxGradientsU[{n_slices}] = {{ {max_grad_u_str} }};
    static const float SliceMaxGradientsV[{n_slices}] = {{ {max_grad_v_str} }};

    inline int32 GetNumSlices() {{ return {n_slices}; }}
    inline float GetUMin() {{ return {u_min:.6f}f; }}
    inline float GetUMax() {{ return {u_max:.6f}f; }}
    inline float GetVMin() {{ return {v_min:.6f}f; }}
    inline float GetVMax() {{ return {v_max:.6f}f; }}
}}
#endif
"""
    with open(header_path, "w", encoding="utf-8") as f:
        f.write(header_content)
    print(f"[Atlas Baker] Generated C++/HLSL header: {header_path}")


def bake_kelvin_wake_atlas(
    froude_slices: List[float] = DEFAULT_FROUDE_SLICES,
    domain_cfg: KelvinDomainConfig = KelvinDomainConfig(u_min=0.0, u_max=10.0, v_min=-3.0, v_max=+3.0, res_u=512, res_v=256),
    output_dir_str: str = "atlas_output"
):
    """Bakes multi-slice Kelvin signed-height and analytical gradient atlas."""
    output_dir = Path(output_dir_str)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"\n=======================================================")
    print(f"[Atlas Baker] Starting Kelvin Wake Gradient Atlas Bake")
    print(f"  Slices ({len(froude_slices)}): {froude_slices}")
    print(f"  Resolution: {domain_cfg.res_u} (U) x {domain_cfg.res_v} (V)")
    print(f"  Channels: 4 (R=Z, G=dZ/du, B=dZ/dv, A=Mask)")
    print(f"=======================================================")

    evaluator = GaussLegendreVectorizedEvaluator(n_sub=8, n_nodes_per_sub=128)
    U, V = domain_cfg.get_coordinate_grids()

    n_slices = len(froude_slices)
    # Shape: (n_slices, res_u, res_v, 4)
    atlas_rgba = np.zeros((n_slices, domain_cfg.res_u, domain_cfg.res_v, 4), dtype=np.float32)
    
    slice_stats = []
    global_max_abs = 0.0

    for i, Fr in enumerate(froude_slices):
        print(f"[Atlas Baker] Computing Slice [{i+1}/{n_slices}] Fr = {Fr:.2f} (Z + dZ/du + dZ/dv) ...")
        Z, dZu, dZv = evaluator.evaluate_all(U, V, Fr)
        
        z_min, z_max = float(np.min(Z)), float(np.max(Z))
        z_abs = max(abs(z_min), abs(z_max), 1e-6)
        global_max_abs = max(global_max_abs, z_abs)
        
        dzu_abs = max(abs(float(np.min(dZu))), abs(float(np.max(dZu))))
        dzv_abs = max(abs(float(np.min(dZv))), abs(float(np.max(dZv))))
        
        inv_z_abs = 1.0 / z_abs
        atlas_rgba[i, :, :, 0] = (Z * inv_z_abs).astype(np.float32)
        atlas_rgba[i, :, :, 1] = (dZu * inv_z_abs).astype(np.float32)
        atlas_rgba[i, :, :, 2] = (dZv * inv_z_abs).astype(np.float32)
        atlas_rgba[i, :, :, 3] = 1.0
        
        slice_stats.append({
            "SliceIndex": i,
            "FroudeNumber": Fr,
            "Z_Min": z_min,
            "Z_Max": z_max,
            "Z_AbsMax": z_abs,
            "GradU_AbsMax": dzu_abs,
            "GradV_AbsMax": dzv_abs
        })

    # Save RGBA16F Binary Payload
    atlas_rgba_fp16 = atlas_rgba.astype(np.float16)
    raw_rgba_bytes = atlas_rgba_fp16.tobytes()

    bin_rgba_path = output_dir / "kelvin_wake_atlas_gradient_fp16.bin"
    with open(bin_rgba_path, "wb") as f:
        f.write(raw_rgba_bytes)
    payload_sha256 = hashlib.sha256(raw_rgba_bytes).hexdigest()
    print(f"[Atlas Baker] Written RGBA16F Payload: {bin_rgba_path} ({len(raw_rgba_bytes)} bytes)")

    # Save Single-Channel R16F (Height-only) for backwards-compatibility
    atlas_r16_fp16 = atlas_rgba[:, :, :, 0].astype(np.float16)
    bin_r16_path = output_dir / "kelvin_wake_atlas_fp16.bin"
    with open(bin_r16_path, "wb") as f:
        f.write(atlas_r16_fp16.tobytes())

    meta = {
        "BakerVersion": "M4A_2.0_AnalyticalGradient",
        "PayloadSHA256": payload_sha256,
        "NumSlices": n_slices,
        "ResolutionU": domain_cfg.res_u,
        "ResolutionV": domain_cfg.res_v,
        "Channels": ["R_Height", "G_GradU", "B_GradV", "A_Mask"],
        "BytesPerTexel": 8, # 4 channels x 2 bytes
        "TotalSizeBytes": len(raw_rgba_bytes),
        "Domain": {
            "UMin": domain_cfg.u_min,
            "UMax": domain_cfg.u_max,
            "VMin": domain_cfg.v_min,
            "VMax": domain_cfg.v_max
        },
        "GlobalScaleFactor": float(global_max_abs),
        "FroudeSlices": froude_slices,
        "SliceMaxAmplitudes": [s["Z_AbsMax"] for s in slice_stats],
        "SliceMaxGradientsU": [s["GradU_AbsMax"] for s in slice_stats],
        "SliceMaxGradientsV": [s["GradV_AbsMax"] for s in slice_stats],
        "Slices": slice_stats
    }

    meta_path = output_dir / "kelvin_wake_atlas_meta.json"
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)
    print(f"[Atlas Baker] Saved atlas metadata: {meta_path}")

    header_path = output_dir / "KelvinAtlasGradientConstants.h"
    generate_cpp_hlsl_header(meta, header_path)

    # Generate Montage Preview (Left: Height, Right: Normal RGB)
    print("[Atlas Baker] Generating visual atlas montage preview ...")
    n_cols = 4
    n_rows = (n_slices + n_cols - 1) // n_cols
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(4 * n_cols, 3 * n_rows), dpi=150)
    axes_flat = axes.ravel() if n_slices > 1 else [axes]

    for i in range(len(axes_flat)):
        ax = axes_flat[i]
        if i < n_slices:
            Fr = froude_slices[i]
            dZu = atlas_rgba[i, :, :, 1]
            dZv = atlas_rgba[i, :, :, 2]
            norm_len = np.sqrt(dZu**2 + dZv**2 + 1.0)
            rgb = np.stack([(-dZu / norm_len) * 0.5 + 0.5, (-dZv / norm_len) * 0.5 + 0.5, (1.0 / norm_len) * 0.5 + 0.5], axis=-1)
            
            ax.imshow(
                np.transpose(rgb, (1, 0, 2)),
                extent=[domain_cfg.u_min, domain_cfg.u_max, domain_cfg.v_min, domain_cfg.v_max],
                origin='lower', aspect='equal'
            )
            u_cusp = np.linspace(0, domain_cfg.u_max, 50)
            v_cusp = u_cusp * np.tan(KELVIN_CUSP_ANGLE_RAD)
            ax.plot(u_cusp, v_cusp, 'w--', linewidth=0.8, alpha=0.6)
            ax.plot(u_cusp, -v_cusp, 'w--', linewidth=0.8, alpha=0.6)
            
            ax.set_title(f'Slice {i}: Fr={Fr:.2f} (Normal RGB)', fontsize=9, fontweight='bold')
            ax.set_xticks([0, 5, 10])
            ax.set_yticks([-3, 0, 3])
            ax.tick_params(labelsize=8)
        else:
            ax.axis('off')

    plt.suptitle(f"Kelvin Wake Analytical Gradient Atlas (RGBA16F) - {n_slices} Slices", fontsize=13, fontweight='bold')
    plt.tight_layout()
    preview_path = output_dir / "atlas_slices_preview.png"
    plt.savefig(preview_path)
    plt.close(fig)
    print(f"[Atlas Baker] Saved preview montage: {preview_path}")

    print("[Atlas Baker] Atlas Bake with Gradients completed successfully!\n")
    return meta


if __name__ == "__main__":
    current_dir = Path(__file__).parent
    out_dir = current_dir / "atlas_output"
    bake_kelvin_wake_atlas(output_dir_str=str(out_dir))
