#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

// ?꾨줈?앺듃?먯꽌 ?ъ슜??紐⑤뱺 ?쒓렇瑜??좎뼵

// State (?곹깭 愿???쒓렇)
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Damaged);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Crafting);

// Team  (?쇱븘 援щ텇 愿???쒓렇 - ?寃잜똿 ?꾪꽣留곸슜)
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Player);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Enemy);

// GameplayAbility
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_Active);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_Dead);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_BasicAttack);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_HitReaction);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_TestHit);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayAbility_Equip);

// Event (?대깽??愿???쒓렇)
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Changed);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HandleScan_Start);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HandleScan_End);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ActivateAbility_Equip);

// Data
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Heal);


/* Player */

// ItemSlot - Keyboard Tag
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Item);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Item_1);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Item_2);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Item_3);

// Crafter Skill - Keyboard Tag
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Crafter_R);

/*Item Identify Tag */
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_TestCrafted);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Grenade);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Sword);

// Tool
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Tool);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Tool_Grenade);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Tool_TestRed);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Tool_TestBlue);

// Material
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Ore);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Woods);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Cloths);

/* Enemy */

// Enemy Item
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EnemyWeapon_Sword);

// Enemy type
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Type_Animal_Test);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Type_Undead_Test);

/* Gameplay Event Tag */
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Input_MouseLeftClick);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Input_MouseLeftClick_Released);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Input_MouseRightClick);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_ThrowGrenade);

/* Default - Keyboard & Mouse */
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Default_Mouse);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Default_Mouse_LeftClick);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Default_Mouse_RightClick);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Default_F);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Default_ESC);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_Default_Space);

/* UI Input */
// Ex. I >> Inventory, M >> Map, E >> Equipment
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Key_UI_I);


/* Ability */
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Item_Equipped);


/* Feature Class */
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Crafter);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Class_Attacker);


/* Interaction */
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_PickUp);
ARTISTICSWCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Craft);

